- name: Install global composer packages
  composer:
    command: require
    global_command: yes
    arguments: "{{ item }}"
  with_items: "{{ composer_packages }}"

- name: Set global composer configuration options
  template:
    src: composer.json.j2
    dest: "{{ composer_dir }}/config.json"
