- name: Install zipped mac apps
  unarchive:
    src: "{{ item.path }}"
    dest: "{{ mac_applications_dir }}"
    creates: "{{ mac_applications_dir }}/{{ item.creates | default('missing') }}"
  with_items: "{{ mac_apps }}"
  when: "item.path | search('.zip')"

- name: Install pkg mac apps
  command: "installer -pkg \"{{ item.path }}\" -target /"
  args:
    creates: "{{ mac_applications_dir }}/{{ item.creates | default(missing) }}"
  become: yes
  with_items: "{{ mac_apps }}"
  when: "item.path | search('.pkg')"
