- name: Install dotfiles using ansible
  hosts: localhost
  connection: local
  vars_files:
    - variables/helpers.yml
    - variables/aliases.yml
    - variables/bin.yml
    - variables/identity.yml
    - variables/paths.yml
    - variables/shell.yml
    - variables/software.yml
    - variables/linux/software.yml
    - variables/mac/defaults.yml
    - variables/mac/software.yml
  vars_prompt:
    - name: ansible_become_pass
      prompt: Sudo password needed for some tasks
      private: yes
  roles:
    - role: software
      tags: [software]
    - role: mac-defaults
      tags: [defaults]
    - role: rc
      tags: [rc, shell]
