- name: Update homebrew
  command: brew update

- name: Ensure configured homebrew taps are installed
  homebrew_tap:
    tap: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: Install homebrew packages
  homebrew:
    name: "{{ homebrew_apps }}"
    state: present

- name: Install homebrew cask applications
  homebrew_cask:
    name: "{{ homebrew_cask_apps }}"
    state: present
