mac_defaults:
  # Finder settings
  - domain: com.apple.finder
    key: _FXSortFoldersFirst
    value: 1
  - domain: com.apple.finder
    key: ShowExternalHardDrivesOnDesktop
    value: 0
  - domain: com.apple.finder
    key: ShowHardDrivesOnDesktop
    value: 0
  - domain: com.apple.finder
    key: ShowMountedServersOnDesktop
    value: 0
  - domain: com.apple.finder
    key: ShowRemovableMediaOnDesktop
    value: 0
  - domain: com.apple.finder
    key: NewWindowTarget
    value: '"PfHm"'
  - domain: com.apple.finder
    key: NewWindowTargetPath
    value: '"file:///Users/jsphpl/"'

  # Disable Siri
  - domain: com.apple.siricore.fides
    key: DES Lottery Win Override Enabled
    value: 0
  - domain: com.apple.siricore.fides
    key: DES Recording Enabled
    value: 0
  - domain: com.apple.Siri
    key: StatusMenuVisible
    value: 0

  # Keyboard repeat rate and delay
  - domain: -g
    key: InitialKeyRepeat
    value: -int 15
  - domain: -g
    key: KeyRepeat
    value: -int 2

  # Trackpad settings
  - domain: -g
    key: com.apple.trackpad.scaling
    value: 2
  - domain: com.apple.AppleMultitouchTrackpad
    key: Clicking
    value: 1
  - domain: com.apple.AppleMultitouchTrackpad
    key: TrackpadThreeFingerHorizSwipeGesture
    value: 0
  - domain: com.apple.AppleMultitouchTrackpad
    key: TrackpadThreeFingerVertSwipeGesture
    value: 0
  - domain: com.apple.AppleMultitouchTrackpad
    key: TrackpadThreeFingerTapGesture
    value: 0
  - domain: com.apple.AppleMultitouchTrackpad
    key: TrackpadThreeFingerDrag
    value: 1

  # Prevent creation of .DS_Store files on network drives
  - domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    value: true

  # Dock
  - domain: com.apple.dock
    key: autohide
    value: 1
  - domain: com.apple.dock
    key: orientation
    value: left

  # Allow tab-navigation of dialog window actions
  - domain: NSGlobalDomain
    key: AppleKeyboardUIMode
    value: 3

  # Hide Pastebot Menubar and Dock icon
  - domain: com.tapbots.Pastebot2Mac
    key: UIVisibilityState
    value: 10
